version: "2"
services:
  centos5:
    build:
      dockerfile: Dockerfile.centos5
      context: .
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    command: "cp -a /out/rbenv-ruby-${RUBY_VERSION}.tar.gz /tmp"
    volumes:
      - .:/tmp:rw

  centos6:
    build:
      dockerfile: Dockerfile.centos6
      context: .
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    command: "cp -a /out/rbenv-ruby-${RUBY_VERSION}.tar.gz /tmp"
    volumes:
      - .:/tmp:rw

  centos7:
    build:
      dockerfile: Dockerfile.centos7
      context: .
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    command: "cp -a /out/rbenv-ruby-${RUBY_VERSION}.tar.gz /tmp"
    volumes:
      - .:/tmp:rw
